### ISSUE TITLE
Locating USB after mount

### ISSUE THREAD

**Issue by lotusronin** [LUGatGT/linux-freestyle#10]
The UI just needs the path to the usb to give to Ddd to have it run, but I am not sure where I'm supposed to get that from. Is there some simple shell command that can tell us that? As it is, DDLauncher::getUSBPath() is unimplemented. See the UI branch in question or #9 for the class/method.

**Comment by jgkamat** [comment]
I think the udev script should handle that. Ideally there would be some sort of trigger that udev would send you but I have no idea how that would be implemented.
